spring:
  application:
    name: dashboard
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  jpa:
    open-in-view: false

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true